version: "3"

volumes:
  consul_server_1:
  consul_server_2:
  consul_server_3:
  consul_client_1:
  consul_client_2:
  consul_client_3:
  vault_server_1:
  vault_server_2:
  vault_server_3:

networks: 
  network:

services:

  consul-server-1:
    build: consul/
    container_name: consul-server-1
    hostname: consul-server-1
    environment:
      - DATACENTER=test
      - JOIN1=consul-server-1
      - JOIN2=consul-server-2
      - JOIN3=consul-server-3
      - NODE_NAME=server-1
    volumes:
      - consul_server_1:/consul/data
    networks: 
      - network

  consul-server-2:
    build: consul/
    container_name: consul-server-2
    hostname: consul-server-2
    environment:
      - DATACENTER=test
      - JOIN1=consul-server-1
      - JOIN2=consul-server-2
      - JOIN3=consul-server-3
      - NODE_NAME=server-2
    volumes:
      - consul_server_2:/consul/data
    networks: 
      - network

  consul-server-3:
    build: consul/
    container_name: consul-server-3
    hostname: consul-server-3
    environment:
      - DATACENTER=test
      - JOIN1=consul-server-1
      - JOIN2=consul-server-2
      - JOIN3=consul-server-3
      - NODE_NAME=server-3
    volumes:
      - consul_server_3:/consul/data
    networks: 
      - network

  vault-server-1:
    build: .
    container_name: vault-server-1
    hostname: vault-server-1
    cap_add:
      - IPC_LOCK
    environment:
      - DATACENTER=test
      - JOIN1=consul-server-1
      - JOIN2=consul-server-2
      - JOIN3=consul-server-3
      - NODE_NAME=client-1
    volumes:
      - consul_client_1:/consul/data
      - vault_server_1:/vault/data
    networks:
      - network

  vault-server-2:
    build: .
    container_name: vault-server-2
    hostname: vault-server-2
    cap_add:
      - IPC_LOCK
    environment:
      - DATACENTER=test
      - JOIN1=consul-server-1
      - JOIN2=consul-server-2
      - JOIN3=consul-server-3
      - NODE_NAME=client-2
    volumes:
      - consul_client_2:/consul/data
      - vault_server_2:/vault/data
    networks:
      - network

  vault-server-3:
    build: .
    container_name: vault-server-3
    hostname: vault-server-3
    cap_add:
      - IPC_LOCK
    environment:
      - DATACENTER=test
      - JOIN1=consul-server-1
      - JOIN2=consul-server-2
      - JOIN3=consul-server-3
      - NODE_NAME=client-3
    volumes:
      - consul_client_3:/consul/data
      - vault_server_3:/vault/data
    networks:
      - network
